export type SmartProduct={id:number;categoryId:number;name:string;description?:string|null;price:string;image?:string|null;stock?:number;isActive?:boolean};
export type AssistantResult={text:string;products:SmartProduct[];suggestedQuestions:string[];intent:"search"|"category"|"meal"|"budget"|"help"};
const norm=(v:string)=>v.toLowerCase().replace(/[إأآا]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[^\u0600-\u06ffa-z0-9\s]/gi," ").replace(/\s+/g," ").trim();
const groups:Record<string,string[]>={ألبان:["لبن","حليب","زبادي","رايب","لبنه","قشطه","كريمه"],جبن:["جبنه","جبن","شيدر","رومي","فيتا","موتزاريلا","قريش","مثلثات"],منظفات:["منظف","منظفات","مسحوق","غسيل","كلور","مطهر","صابون","معطر","ملمع"],مشروبات:["عصير","مياه","ماء","مشروب","بيبسي","كوكا","شاي","قهوه","نسكافيه"],سناكس:["شيبسي","بسكويت","ويفر","شوكولاته","سناك","مقرمشات"],بقالة:["ارز","سكر","مكرونه","زيت","دقيق","صلصه","تونه","فول","عدس","فاصوليا","لوبيا"]};
const meals:Record<"فطار"|"غداء"|"عشاء",string[]>={فطار:["عيش","خبز","توست","مربى","مربي","حلاوه","جبنه","جبن","لبن","حليب","بيض","فول","عسل","زعتر","شاي","قهوه","زبادي"],غداء:["ارز","عدس","عيش","خبز","توست","تونه","فاصوليا","لوبيا","فراخ","دجاج","صدور","لحمه","رنجه","رنجة","بطاطس","مكرونه"],عشاء:["عيش","خبز","توست","مربى","مربي","حلاوه","جبنه","جبن","لبن","حليب","بيض","فول","تونه","رنجه","زبادي","عسل","شاي"]};
const exclusions:Record<"فطار"|"غداء"|"عشاء",string[]>={فطار:["مسحوق","منظف","كلور","صابون","ارز","مكرونه","زيت","صلصه","دقيق","فاصوليا","لوبيا"],غداء:["مسحوق","منظف","كلور","صابون","معطر"],عشاء:["مسحوق","منظف","كلور","صابون","ارز","مكرونه","زيت","صلصه","دقيق"]};
const available=(p:SmartProduct)=>p.isActive!==false&&(p.stock===undefined||p.stock>0);
const name=(p:SmartProduct)=>norm(p.name);
const hay=(p:SmartProduct)=>norm([p.name,p.description||""].join(" "));
const price=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const has=(p:SmartProduct,terms:string[])=>terms.some(t=>name(p).includes(norm(t)));
const budget=(q:string)=>{const m=norm(q).match(/(?:حدود|ميزانيه|بميزانيه|لحد|اقل من|تحت)\s*\D{0,6}(\d{2,5})/);return m?Number(m[1]):null};
const people=(q:string)=>{const m=norm(q).match(/(\d+)\s*(?:شخص|افراد|فرد|اشخاص)/);return m?Number(m[1]):null};
const rank=(ps:SmartProduct[],q:string)=>{const stop=["عايز","عاوزه","عاوز","عندي","عندكم","ممكن","ايه","من","في","لو","طب","حاجه","حاجة","محتاج"],ts=norm(q).split(" ").filter(x=>x.length>1&&!stop.includes(x));return ps.filter(available).map(p=>({p,s:ts.reduce((n,t)=>n+(name(p).includes(t)?6:hay(p).includes(t)?2:0),0)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s||price(a.p.price)-price(b.p.price)).slice(0,15).map(x=>x.p)};
const meal=(ps:SmartProduct[],m:"فطار"|"غداء"|"عشاء",b:number|null,n:number|null)=>{const excluded=exclusions[m];const mult=n&&n>2?Math.min(2,n/2):1;const pool=ps.filter(p=>available(p)&&has(p,meals[m])&&!excluded.some(t=>name(p).includes(norm(t)))).sort((a,b)=>price(a.price)-price(b.price));const out:SmartProduct[]=[];let total=0;for(const p of pool){if(out.length>=15)break;const c=price(p.price)*mult;if(total+c<=(b??Infinity)){out.push(p);total+=c}}return {out,total,pool};};
const fallback="فضلاً أضف طلبك من الرئيسية، لا أستطيع الوصول إلى طلبك بهذه الصيغة حاليًا.";
export function askSmartAssistant(q:string,products:SmartProduct[],history:string[]=[]):AssistantResult{const x=norm(q),ps=products.filter(available);if(!x)return{text:"أنا جاهز. قولّي عايز تشتري إيه، وأنا أساعدك من منتجات الوحيد ماركت الموجودة حاليًا.",products:[],suggestedQuestions:["اقترحلي فطار","اقترحلي غدا","اقترحلي عشا","عايز حاجة اقتصادية"],intent:"help"};
const context=norm(history.slice(-6).join(" "));const b=budget(x),n=people(x),m=x.includes("فطار")?"فطار":x.includes("غدا")||x.includes("غداء")?"غداء":x.includes("عشا")||x.includes("عشاء")?"عشاء":null;
if(m){const {out,pool}=meal(ps,m,b,n);const scaled=out.reduce((s,p)=>s+price(p.price)*(n&&n>2?Math.min(2,n/2):1),0);return{text:out.length?"تمام. فهمت إنك بتدور على "+m+"، فدي اختيارات مناسبة فعلًا للوجبة من المنتجات الموجودة عندنا."+(n?" مناسبة لحوالي "+n+" أفراد.":"")+(b?" وفي حدود "+b+" جنيه.":"")+" الإجمالي التقريبي: "+scaled.toFixed(2)+" ج.م.":pool.length?"عندي منتجات مرتبطة بـ"+m+"، لكن الميزانية الحالية لا تكفي لاقتراح مناسب.":"مش ظاهر عندي حاليًا منتجات كفاية لبناء اقتراح "+m+".",products:out,suggestedQuestions:["بدّل الاختيارات","خليه أوفر","زود اختيارات","إضافة الكل للسلة"],intent:b?"budget":"meal"}}
const cheap=x.includes("ارخص")||x.includes("اقتصادي")||x.includes("اوفر")||x.includes("موفر");
if((cheap||x.includes("بدل")||x.includes("بديل"))&&context){const out=rank(ps,context).sort((a,b)=>price(a.price)-price(b.price));if(out.length)return{text:cheap?"تمام، دي اختيارات أوفر من الموجود عندنا.":"أكيد، دي بدائل من نفس الكتالوج.",products:out,suggestedQuestions:["الأرخص؟","ضيف ده للسلة","زود اختيارات","اقترحلي حاجة تانية"],intent:"budget"}}
const cat=Object.entries(groups).find(([k,t])=>t.some(v=>x.includes(norm(v))));if(cat){const out=ps.filter(p=>has(p,cat[1])).sort((a,b)=>price(a.price)-price(b.price)).slice(0,15);return out.length?{text:"تمام، دي المنتجات المتاحة حاليًا في "+cat[0]+" — عندك اختيارات كتير، وكل منتج عليه علامة + للإضافة للسلة.",products:out,suggestedQuestions:["الأرخص؟","عندكم أنواع تانية؟","ضيف الكل للسلة","إيه المناسب للفطار؟"],intent:"category"}:{text:fallback,products:[],suggestedQuestions:["اقترحلي فطار","اقترحلي غدا","إيه منتجات الألبان؟"],intent:"help"}}
const out=rank(ps,x);if(out.length)return{text:"لقيت لك اختيارات من الكتالوج الحالي. اختار اللي يعجبك بعلامة +، ولو عايزني أغيّرها أو أدوّر على الأرخص قولّي.",products:out,suggestedQuestions:["الأرخص؟","عندك بدائل؟","اقترحلي فطار","إضافة الكل للسلة"],intent:cheap?"budget":"search"};
return{text:fallback,products:[],suggestedQuestions:["اقترحلي فطار","اقترحلي غدا","اقترحلي عشا","إيه منتجات الألبان؟"],intent:"help"}}
export const toCartItem=(p:SmartProduct)=>({id:Number(p.id),categoryId:Number(p.categoryId),name:String(p.name),price:String(p.price),image:p.image?String(p.image):undefined,quantity:1});