export type SmartProduct={id:number;categoryId:number;name:string;description?:string|null;price:string;image?:string|null;stock?:number;isActive?:boolean};
export type AssistantResult={text:string;products:SmartProduct[];suggestedQuestions:string[];intent:"search"|"category"|"meal"|"budget"|"help"};
const norm=(v:string)=>v.toLowerCase().replace(/[إأآا]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[^\u0600-\u06ffa-z0-9\s]/gi," ").replace(/\s+/g," ").trim();
const terms:Record<string,string[]>={ألبان:["لبن","حليب","زبادي","رايب","لبنه","كريمه","قشطه","جبنه","جبن"],جبن:["جبنه","جبن","شيدر","رومي","فيتا","موتزاريلا","قريش","مثلثات"],منظفات:["منظف","منظفات","مسحوق","غسيل","كلور","مطهر","صابون","معطر","ملمع"],مشروبات:["عصير","مياه","ماء","مشروب","بيبسي","كوكا","شاي","قهوه","نسكافيه"],سناكس:["شيبسي","بسكويت","ويفر","شوكولاته","سناك","مقرمشات"],بقالة:["ارز","سكر","مكرونه","زيت","دقيق","صلصه","تونه","فول","عدس"],فطار:["بيض","لبن","حليب","جبنه","جبن","مربى","مربي","عسل","فول","زعتر","خبز","عيش","توست","شاي","قهوه","نسكافيه","زبادي"],غداء:["ارز","مكرونه","صلصه","زيت","فراخ","دجاج","لحمه","تونه","خضار"],عشاء:["جبنه","جبن","بيض","تونه","زبادي","خبز","عيش","توست","لبن","حليب"]};
const mealExclusions:Record<"فطار"|"غداء"|"عشاء",string[]>={فطار:["ارز","دقيق","فاصوليا","مكرونه","صلصه","زيت","عدس","خضار","مسحوق","منظف"],غداء:["مسحوق","منظف","صابون","شاي","قهوه"],عشاء:["مسحوق","منظف","صابون"]};
const available=(p:SmartProduct)=>p.isActive!==false&&(p.stock===undefined||p.stock>0);
const hay=(p:SmartProduct)=>norm([p.name,p.description||""].join(" "));
const name=(p:SmartProduct)=>norm(p.name);
const has=(p:SmartProduct,ts:string[])=>ts.some(t=>hay(p).includes(norm(t)));
const price=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const budget=(q:string)=>{const m=norm(q).match(/(?:حدود|ميزانيه|بميزانيه|لحد|اقل من|تحت)\s*\D{0,6}(\d{2,5})/);return m?Number(m[1]):null};
const people=(q:string)=>{const m=norm(q).match(/(\d+)\s*(?:شخص|افراد|فرد|اشخاص)/);return m?Number(m[1]):null};
const rank=(ps:SmartProduct[],q:string)=>{const stop=["عايز","عاوزه","عاوز","عندي","عندكم","ممكن","ايه","من","في","لو","طب","حاجه","حاجة"],ts=norm(q).split(" ").filter(x=>x.length>1&&!stop.includes(x));return ps.filter(available).map(p=>({p,s:ts.reduce((n,t)=>n+(name(p).includes(t)?5:hay(p).includes(t)?2:0),0)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s||price(a.p.price)-price(b.p.price)).slice(0,8).map(x=>x.p)};
const meal=(ps:SmartProduct[],m:"فطار"|"غداء"|"عشاء",b:number|null,n:number|null)=>{const mult=n&&n>2?Math.min(2,n/2):1;const excluded=mealExclusions[m];const pool=ps.filter(p=>available(p)&&terms[m].some(t=>name(p).includes(norm(t)))&&!excluded.some(t=>name(p).includes(norm(t)))).sort((a,b)=>price(a.price)-price(b.price));const out:SmartProduct[]=[];let total=0;for(const p of pool){if(out.length>=5)break;const c=price(p.price)*mult;if(total+c<=(b??Infinity)){out.push(p);total+=c}}return {out,total,pool};};
export function askSmartAssistant(q:string,products:SmartProduct[]):AssistantResult{const x=norm(q),ps=products.filter(available);if(!x)return{text:"أنا جاهز. اسألني عن أي منتج أو قسم، أو قولي عايز فطار أو غدا أو عشا وأنا أرتب لك اختيارات من الموجود حاليًا.",products:[],suggestedQuestions:["إيه منتجات الألبان؟","اقترحلي فطار","عايز منظفات","عايز حاجة اقتصادية"],intent:"help"};const b=budget(x),n=people(x),m=x.includes("فطار")?"فطار":x.includes("غدا")||x.includes("غداء")?"غداء":x.includes("عشا")||x.includes("عشاء")?"عشاء":null;if(m){const {out,total,pool}=meal(ps,m,b,n);const scaledTotal=out.reduce((s,p)=>s+price(p.price)*(n&&n>2?Math.min(2,n/2):1),0);const text=out.length?("تمام، فهمت إنك عايز "+m+" — فاختارت لك حاجات مرتبطة بالفطار نفسه، مش مكونات طبخ عامة.")+(n?" مناسب لـ"+n+" أفراد":"")+(b?" وفي حدود "+b+" جنيه":"")+". الإجمالي التقريبي: "+scaledTotal.toFixed(2)+" ج.م.":b&&pool.length?"عندي اختيارات مناسبة لـ"+m+" لكن مش هاقترح عليك حاجات تتخطى ميزانيتك. زوّد الميزانية شوية أو قولي عدد الأشخاص.":"مش لاقي حاليًا منتجات مناسبة كفاية لـ"+m+" من الكتالوج الحالي.";return{text,products:out,suggestedQuestions:["بدّل الاختيارات","خليه اقتصادي","إيه الموجود من الجبن؟","إضافة الاختيارات للسلة"],intent:b?"budget":"meal"}}const cat=Object.entries(terms).find(([k,t])=>!["فطار","غداء","عشاء"].includes(k)&&t.some(v=>x.includes(norm(v))));if(cat){const out=ps.filter(p=>has(p,cat[1])).slice(0,8);return{text:out.length?"لقيت لك "+out.length+" منتجات مرتبطة بـ"+cat[0]+" من الكتالوج الحالي.":"مش لاقي منتجات متاحة حاليًا مرتبطة بـ"+cat[0]+".",products:out,suggestedQuestions:["الأرخص فيهم؟","عندكم أنواع تانية؟","ضيف ده للسلة","إيه المناسب للفطار؟"],intent:"category"}}const out=rank(ps,x),cheap=x.includes("ارخص")||x.includes("اقتصادي")||x.includes("موفر"),ordered=cheap?[...out].sort((a,b)=>price(a.price)-price(b.price)):out;return ordered.length?{text:"لقيت لك "+ordered.length+" اختيار من المنتجات الموجودة حاليًا. "+(cheap?"رتبتهم من الأقل سعرًا.":"تقدر تضيف أي اختيار للسلة."),products:ordered,suggestedQuestions:["الأرخص؟","عندكم بدائل؟","اقترحلي فطار","إضافة الاختيارات للسلة"],intent:cheap?"budget":"search"}:{text:"مش لاقي تطابق مباشر. جرّب اسم المنتج أو القسم، أو قولّي: فطار، غدا، عشا، ألبان، جبن، منظفات، أو مشروبات.",products:[],suggestedQuestions:["إيه منتجات الألبان؟","إيه أنواع الجبن؟","عايز منظفات","اقترحلي غدا"],intent:"help"}}
export const toCartItem=(p:SmartProduct)=>({id:Number(p.id),categoryId:Number(p.categoryId),name:String(p.name),price:String(p.price),image:p.image?String(p.image):undefined,quantity:1});